# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Perry's Corner
email: perrie.studios20@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://perriestudios.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nah
github_username:  perriestudios

# Build settings
remote_theme: pmarsceill/just-the-docs

#theme: jekyll-theme-just-the-docs
#plugins:
#  - jekyll-feed

# Enable or disable the site search
search_enabled: true

# Aux links for upper right navigation link
aux_links:
  "Go to GitHub profile >":
    - "https://github.com/perriestudios"

# Include pages into processing
include: ["_pages", "_posts"]

# Footer content appears at the bottom of every page's main content
#footer_content: "Copyright &copy; 2021 Andrea Pasqualini. Distributed under the <a href=\"https://github.com/AndreaPasqualini/andreapasqualini.github.io/tree/master/LICENSE\">

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false/nil
heading_anchors: true

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-153303214-1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
